version: '3.8'
services:
  preparer:
      restart: no
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - .:/app
      networks:
        - detector-network
      environment:
        - RUN_AS=PREPARER

  testserver:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 8000:8000
    networks:
      - detector-network
    environment:
      - RUN_AS=TEST_SERVER

  detector:
    restart: no
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    volumes:
      - .:/app
    networks:
      - detector-network
    depends_on:
      preparer:
        condition: service_completed_successfully

networks:
  detector-network:
    driver: bridge