version: '3.8'
services:
  testserver:
    build:
      context: .
      dockerfile: test/Dockerfile
    volumes:
      - .:/app
    ports:
      - 8000:8000
    networks:
      - detector-network
  detector:
    build:
      context: .
      dockerfile: src/Dockerfile
    volumes:
      - .:/app
    ports:
      - 8001:8001
    networks:
      - detector-network
    depends_on:
      - testserver
networks:
  detector-network:
    driver: bridge