version: '3.8'
services:
  testserver:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 8000:8000
    networks:
      - detector-network
  detector:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    networks:
      - detector-network
    depends_on:
      - testserver
networks:
  detector-network:
    driver: bridge