apiVersion: v1
kind: Namespace
metadata:
  name: watcher

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: watcher-deployment
  namespace: watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watcher
  template:
    metadata:
      labels:
        app: watcher
    spec:
      serviceAccountName: watcher-service
      containers:
      - name: watcher
        image: 339713007259.dkr.ecr.us-east-1.amazonaws.com/watcher:latest
