apiVersion: v1
kind: Namespace
metadata:
  name: detector

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: detector-deployment
  namespace: detector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: detector
  template:
    metadata:
      labels:
        app: detector
    spec:
      containers:
      - name: detector
        image: 339713007259.dkr.ecr.us-east-1.amazonaws.com/detector:latest
