name: Build 
run-name: ${{ github.actor }} is building ${{ github.repository }}
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo
        uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t detector .

      - name: Run pytest
        run: docker run detector pytest ./test -v

      - name: Run pylint
        run: docker run detector pylint ./src  
  